### ISSUE TITLE
UART No and other pins

### ISSUE THREAD

**Issue by Tatovi** [MaJerle/GSM_AT_Lib#46]
How can I change UART number and other pins ?

**Comment by MaJerle** [comment]
THat's up to you to dig-in low-level part. You may take an example and open its low-level config, then change GPIO and UART settings + potentially DMA config for your MCU.

https://github.com/MaJerle/lwgsm/blob/develop/lwgsm/src/system/lwgsm_ll_stm32.c for STM32 example
