### ISSUE TITLE
What are the hardware requirements 

### ISSUE THREAD

**Issue by adam-esp** [MaJerle/GSM_AT_Lib#52]
RAM 
ROM
I/O
?

**Comment by MaJerle** [comment]
Based on arch and your system implementation.

**Comment by adam-esp** [comment]
I understand but how much ROM do I need for the LWgsm library? 
Will the Cortex M0 do it?

**Comment by MaJerle** [comment]
This is not enough info. What is the arch you are using and what configuration would it be?

Using full configuration with GCC v9 for ARM, it took `21.34kB` of ROM memory. With full optimization (for size), it took `13kB`. This includes only LwGSM part and not low-level functions that are system important.

**Comment by adam-esp** [comment]
STM32Fxxx will only handle lwgsm support and communicate with ESP32 over SPI. I have too little I / O on ESP32, that's why this STM32.
Do you think that 64kB ROM and 32kB RAM should be enough?

**Comment by MaJerle** [comment]
Seems OK for me.
