### ISSUE TITLE
MQTT not send data

### ISSUE THREAD

**Issue by aminmokhtari94** [MaJerle/GSM_AT_Lib#65]
Hi Mr. Tilen,
I'm using lwgsm on esp8266_rtos_sdk & sim868
the problem is on mqtt, it's connect to the server but hangs on Poll and does not send any data!
Best Regards

![image](https://user-images.githubusercontent.com/41728922/134495857-0cf36ddc-190d-40dd-8110-378caf97f305.png)

**Comment by MaJerle** [comment]
I can see you print every received character on console, which is very good. I don't see that you actually send ">" character to stack.

App waits "> " 2 characters before AT+CIPSEND accepts data.

Could you also add a print info of data being sent from MCU to device?

**Comment by aminmokhtari94** [comment]
Green lines are data that sent from MCU to Sim and whites are received.
Sim waiting for data by sending > but MCU don't do anything!
Am I right?

**Comment by MaJerle** [comment]
Are you sure that ">" is going to process function? Can you debug whats going on?

**Comment by aminmokhtari94** [comment]
Unfortunately i cant debug whats going on but yes it's work with netconn_client and sent http get request but for mqtt it's not.

![image](https://user-images.githubusercontent.com/41728922/134759391-24aca67b-9e12-4c03-9b32-2e2502ff5d59.png)

**Comment by aminmokhtari94** [comment]
The problem was the my low level send_data function, solved!
