### ISSUE TITLE
Wrong data send to MODEM UART

### ISSUE THREAD

**Issue by Spider84** [MaJerle/GSM_AT_Lib#7]
`ATE1
OK
AT+CFUN=1
OK
AT+CMEE=1
OK
AT+CGMI
SIMCOM_Ltd

OK
AT+CGMM
SIMCOM_SIM868

OK
AT+CGSN
867010032343809

OK
AT+CGMR
Revision:1418B03SIM868M32_BT

OK
AT+CREG}1
+CME ERROR: 100
AT+CLCC}1
+CME ERROR: 100
AT+CPI
+CME ERROR: 100`

Why some times sends '}'?
or
AT+CPI instead AT+CPIN?

**Comment by MaJerle** [comment]
Depends on your low-level driver implementation. Maybe baudrate and clock mismatch.

**Comment by Spider84** [comment]
I was strange communication problems on 115200, on 57600 all work fine.
Now I have other problem.....
