### ISSUE TITLE
Server API?

### ISSUE THREAD

**Issue by fizzyade** [MaJerle/GSM_AT_Lib#78]
The documentation states that lwgsm supports both client and server modes and that the api for send/receive is the same, but I can't find any information on how you actually start a server listening and there are no examples of server mode, only client.

Do you have any examples or where can I find the relevant information for starting a server listening?

**Comment by MaJerle** [comment]
I confirm there is absolutely no server API included, even if netconn could quickly support it. Reason is simple, getting static IP address for modem and get network operator to open you socket access is usually a mission impossible.

It was not possible for me to even test it. A docs is potentially a copy-paste mistake from LwESP library.

Btw, I am considering to rename library to LwCELL, (cellular), to allow support for more modems with more generic name. It will require extensive work to do so.
