### ISSUE TITLE
High RAM usage for ESP32 port 

### ISSUE THREAD

**Issue by devprofile98** [MaJerle/GSM_AT_Lib#91]
Hi, as you can see in this [https://github.com/MaJerle/lwcell/blob/355380a54aabda0279fcc9a7ac0bcd2df0d1f018/lwcell/src/system/lwcell_ll_esp32.c#L152](url), you are allocating `0x10000 ( ~ 65KB)` of device ram for LWCELL memory, I checked the `stm32` port also but you used only `0x1000` bytes for its memory,  is this intentional? or should we fix it? it is using about **80%** of our device DRAM.
Thank you.

**Comment by MaJerle** [comment]
@devprofile98 this is the memory that is used for buffer memory allocation functions to allocate/deallocate memory from/to, mostly for data RX packet reasons. It can easily be reduced to about 4kB for a start, or maybe 8kB, and slowly decreased over the time.

**Comment by devprofile98** [comment]
Thanks! That freed up a lot of memory! 😄
